--CREATE TABLE EMP AS SELECT * FROM EMPLOYEES;
--ALTER TABLE EMP ADD STARS VARCHAR2(100);
DESCRIBE EMP;
DECLARE
  EMPNO EMP.EMPLOYEE_ID%TYPE := 176;
  ASTERISK EMP.STARS%TYPE;
  SAL EMP.SALARY%TYPE;
BEGIN
  
END;
/