CREATE OR REPLACE FUNCTION GET_ANNUAL_COMP
 (salary employees.salary%TYPE, comissao NUMBER) RETURN NUMBER IS
BEGIN
  return salary * comissao * 12;
END GET_ANNUAL_COMP;
/


select EMPLOYEE_ID, FIRST_NAME, SALARY, GET_ANNUAL_COMP(SALARY, 0.10) as "SALÁRIO ANUAL"  from EMPLOYEES ;