SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEED OFF

ACCEPT pID_CD PROMPT 'ID_CD';
ACCEPT pNM_CD CHAR PROMPT 'NM_CD';
ACCEPT pNM_ARTISTA CHAR PROMPT 'NM_ARTISTA';
ACCEPT pVL_CD PROMPT 'VL_CD';
ACCEPT pTP_CD PROMPT 'TP_CD';
ACCEPT pCATEGORIA CHAR PROMPT 'CATEGORIA';

DECLARE
  v_ID_CD TAB_CD.ID_CD%TYPE := &pID_CD;
  v_NM_CD TAB_CD.NM_CD%TYPE := &pNM_CD;
  v_NM_ARTISTA TAB_CD.NM_ARTISTA%TYPE := &pNM_ARTISTA;
  v_VL_CD TAB_CD.VL_CD%TYPE := &pVL_CD;
  v_TP_CD TAB_CD.TP_CD%TYPE := &pTP_CD;
  v_CATEGORIA TAB_CD.CATEGORIA%TYPE := &pCATEGORIA;
  e_invalid_tp_cd EXCEPTION;
  search_tp_cd TAB_TP_CD.TP_CD%TYPE;
BEGIN
  select TP_CD into search_tp_cd from TAB_TP_CD where TP_CD = v_TP_CD;

  insert into TAB_CD values(v_ID_CD, v_NM_CD, v_NM_ARTISTA, v_VL_CD, v_TP_CD, v_CATEGORIA);
  
  commit;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Tipo de cd inválido');
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE(SQLCODE);
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/